import { v4 as uuid } from "uuid";
import { showpiece, clock, plant1, wallDecor } from "../../assets/images";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
export const products = [
  {
    _id: uuid(),
    image: showpiece,
    alt: "show piece",
    name: "Show Piece",
    description: "Set of 3 Astronaut Landing",
    price: 500,
    originalPrice: 1000,
    discount: 50,
    latest: true,
    categoryName: "Show Pieces",
    rating: 4,
  },
  {
    _id: uuid(),
    image: showpiece,
    alt: "Show Piece",
    name: "Show Piece",
    description: "Set of 3 Astronaut Landing",
    price: 1000,
    originalPrice: 1000,
    discount: 40,
    latest: false,
    categoryName: "Show Pieces",
    rating: 3,
  },
  {
    _id: uuid(),
    image: wallDecor,
    alt: "Wall Decor",
    name: "Wall Decor",
    price: 500,
    latest: true,
    categoryName: "Wall Decor",
    rating: 4,
    originalPrice: 1000,
    discount: 45,
    description: "Set of 3 Astronaut Landing",
  },
  {
    _id: uuid(),
    image: wallDecor,
    alt: "wallDecor",
    name: "wallDecor",
    price: 400,
    latest: false,
    categoryName: "Wall Decor",
    rating: 3,
    originalPrice: 800,
    discount: 50,
    description: "Set of 3 Astronaut Landing",
  },
  {
    _id: uuid(),
    image: clock,
    alt: "clock",
    name: "clock",
    price: 200,
    latest: true,
    categoryName: "Clocks",
    rating: 4,
    originalPrice: 400,
    discount: 30,
    description: "Set of 3 Astronaut Landing",
  },
  {
    _id: uuid(),
    image: clock,
    alt: "watch",
    name: "watch",
    price: 800,
    latest: false,
    categoryName: "Clocks",
    rating: 2,
    originalPrice: 1600,
    discount: 35,
    description: "Set of 3 Astronaut Landing",
  },
  {
    _id: uuid(),
    image: plant1,
    alt: "plant",
    name: "Homesake",
    price: 900,
    latest: true,
    categoryName: "Plant & Planters",
    rating: 3,
    originalPrice: 1800,
    discount: 20,
    description: "Artifical flower bunch",
  },
  {
    _id: uuid(),
    image: plant1,
    alt: "plant",
    name: "Dekorly",
    price: 1000,
    latest: false,
    categoryName: "Plant & Planters",
    rating: 4,
    originalPrice: 2000,
    discount: 60,
    description: "Artifical plants with pot",
  },
];
